---
- name: Configure Jenkins Playbook
  hosts: jenkins
  tasks:

    - name: Install Java Requirements
      apt:
        update_cache: yes
        name: default-jdk
      become: yes

    - name: Install Jenkins
      shell: |
        wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key |sudo gpg --dearmor -o /usr/share/keyrings/jenkins.gpg
        sudo sh -c 'echo deb [signed-by=/usr/share/keyrings/jenkins.gpg] http://pkg.jenkins.io/debian-stable binary/ > \
        /etc/apt/sources.list.d/jenkins.list'
        sudo apt update -y
        sudo apt install jenkins -y

    - name: Run Jenkins
      shell: /etc/init.d/jenkins start
      become: yes 
